config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,:controllers => {:registrations => "registrations"}
  resources :domains
  devise_for :users,:controllers => {:registrations => "registrations"}
get 'pages/index'
root to: 'pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

#  devise :database_authenticatable, :registerable,
 #        :recoverable, :rememberable, :trackable, :validatable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable, :lockable
end

app/models/domain.rb
class Domain < ActiveRecord::Base
validates :d_name,  uniqueness: true,:presence => { :message => " cannot be blank" } ,format: { with: /\b(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}
#/^((http|https):\/\/)[a-z0-9]*(\.?[a-z0-9]+)\.[a-z]{2,5}(:[0-9]{1,5})?(\/.)?$/ix#d_name, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:account_update) << :name
end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  before_action :set_domain, only: [:show, :edit, :update, :destroy]



  #Listing Approved and Unapproved Domains

  def index
    @domains = Domain.where(:role=>1)
    @domain = Domain.where(:role=>0)
  end


  #Change from one status to another (for Domains)
  def show
    @page=Domain.find params[:id]
    @p=@page.role
    case @p
      when 0
        @page.update(:role=>1)
      when 1
        @page.update(:role=>0)
      end
      redirect_to :action=>"index"

  end



   #Create a new domain

  def new
    @domain = Domain.new
  end
  def edit
  end
  def create
    @domain = Domain.new(domain_params)
     if @domain.save
         redirect_to :action=>"index"
         flash[:notice] = "Successfully created.." 
      else
         redirect_to :action=>"new"
         flash[:notice] = "Invalid domain name" 
      end
  end


  #Option to update existing domains

  def update
      if @domain.update(domain_params)
          redirect_to :action=>"index"
          flash[:notice] = "Successfully updated.."
      else
          redirect_to :action=>"edit"
          flash[:notice] = "Invalid domain name"
      end
  end

  #Delete the existing domain
  
  def destroy
    @domain.destroy
    redirect_to domains_url
    flash[:notice] = "Deleted successfully"
  end

  private
    def set_domain
      @domain = Domain.find(params[:id])
    end

    def domain_params
      params.require(:domain).permit(:d_name, :role)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
    @domains = Domain.where(:role=>1)
    @domain = Domain.where(:role=>0)
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def new
    super                  #inheriting the class from Device controller
  end

  def create
    super    
      @domain_name=Mail::Address.new(user_params["email"]).domain     #get the domain name from the email entered
      @check_domain_status=Domain.where(:d_name=>@domain_name).pluck(:role)[0]        #checks domains avilability in the Approved/Unapproved List
      @user = User.new(user_params)   #gets user details from the form
        case @check_domain_status
          when 1             #this is for approved domains
            @user.save       #Save the user data
          when 0             #For unapproved domains
            AdminMailer.admin(@domain_name).deliver	   #mail sent to the admin
            flash[:notice] = "Your request was sent to the Admin. Please try again after some time."
        else                 #Not in the Approved/Unapproved List
            flash[:notice] = "oops! Your domain was not accepted"
        end
  end

  def update
    super
  end
private
def user_params
 params.require(:user).permit!
end

end 

app/helpers/application_helper.rb
module ApplicationHelper
def header(text)
  content_for(:header) { text.to_s }
end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :d_name, "Domain Name" %><br>
    <%= f.text_field :d_name, :required=>true ,class: 'form-control'%>
  </div>
<%unless params[:action]=="edit"%>
    <div class="field">
     <%= f.radio_button :role, 1,checked:true %>
    <%= f.label :role_approve, 'Approve' %><br>
    <%= f.radio_button :role, 0 %>  
    <%= label :role_unapprove, 'Unapprove' %>
  </div>
<%end%>
  <div class="actions">
    <%= f.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<div class="col-sm-12">
<div class="col-sm-10">
<h1>Listing Domains</h1></div>
<div class="col-sm-2">
<%= link_to "<i class='fa fa-plus fa-lg' aria-hidden='true'><strong> New Domain</strong></i>".html_safe, new_domain_path %></div>
<div class="row">
        <div class="col-sm-6">

<strong>Approved domains</strong>

<table class="table">
  <thead>
    <tr>
      <th>Domain Name</th>
      <th>Activities</th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.d_name %></td>
        <td><%= link_to "<i class='fa fa-arrow-right fa-lg' aria-hidden='true' style='color:red'></i>".html_safe, domain ,data: {confirm: 'Unapprove this domain?'}%>&nbsp;&nbsp;&nbsp;
        <%= link_to "<i class='fa fa-pencil-square-o fa-lg' aria-hidden='true'></i>".html_safe, edit_domain_path(domain) %>&nbsp;&nbsp;&nbsp;
        <%= link_to "<i class='fa fa-trash-o fa-lg' aria-hidden='true'></i>".html_safe, domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-sm-6">
<strong>Unapproved domains</strong>
<table class="table">
<thead> 
    <tr>
      <th>Domain name</th>
      <th>Activities</th>
    </tr>
  </thead>

  <tbody>
    <% @domain.each do |domain| %>
      <tr>
        <td><%= domain.d_name %></td>
        <td><%= link_to "<i class='fa fa-arrow-left fa-lg' aria-hidden='true' style='color:green'></i>".html_safe, domain , data: {confirm: 'Approve this domain?'}%>&nbsp;&nbsp;&nbsp;
        <%= link_to "<i class='fa fa-pencil-square-o fa-lg' aria-hidden='true'></i>".html_safe, edit_domain_path(domain) %>&nbsp;&nbsp;&nbsp;
        <%= link_to "<i class='fa fa-trash-o fa-lg' aria-hidden='true'></i>".html_safe, domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Chat App', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <%unless admin_signed_in?%>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
       <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
               User
              <span class="caret"></span>
           <ul class="dropdown-menu" role="menu">
         <li><%= link_to 'Sign In ', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        </ul>
      </li>
     <% end %>
      </ul>
      <%end%>
           <%unless user_signed_in?%>
         <ul class="nav navbar-nav pull-right">
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_admin.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_admin_registration_path %></li>
              <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Admin', new_admin_session_path %></li>
        <% end %>
  </ul>
<%end%>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>


</body>
</html>

app/views/pages/index.html.erb
<%if admin_signed_in?%>
<%= render template: "domains/index" %>
<%end%>
<%unless user_signed_in? or admin_signed_in? %>
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'User Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>
<%end%>